image: node:latest

# Pick zero or more services to be used on all builds.
# services:

# This folder is cached between builds
cache:
  paths:
    - node_modules/

# Our asynchronous testing
test_async:
  before_script: 
    - npm uninstall bcrypt
    - npm install bcrypt
    - chmod 0777 ./node_modules/.bin/mocha #grand admin permission to mocha to run test
  script:
    - echo "starting async testing..."
    - npm install #update packages
    - npm test #run the mocha test scripts in the test folder

